apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multiflexi-probe.fullname" . }}
  labels:
    {{- include "multiflexi-probe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "multiflexi-probe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "multiflexi-probe.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "multiflexi-probe.serviceAccountName" . }}
      containers:
        - name: multiflexi-probe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command.enabled }}
          command:
            {{- toYaml .Values.command.value | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "multiflexi-probe.fullname" . }}
            - secretRef:
                name: {{ include "multiflexi-probe.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
