apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "multiflexi-probe.fullname" . }}
  labels:
    {{- include "multiflexi-probe.labels" . | nindent 4 }}
stringData:
  PASSWORD: {{ .Values.secrets.PASSWORD | quote }}
