#!/bin/sh
# postinst script for multiflexi-probe
set -e

. /usr/share/debconf/confmodule

APPLICATION=$(echo "$DPKG_MAINTSCRIPT_PACKAGE" | sed 's/multiflexi-//')
for file in /usr/lib/$APPLICATION/multiflexi/*.app.json
do
	multiflexi-cli application import-json --file $file
done

for file in /usr/lib/$APPLICATION/multiflexi/*.credtype.json
do
	multiflexi-cli crprototype import-json --file $file
done
